apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskconsumer
spec:
  selector:
    matchLabels:
      app: taskconsumer
  template:
    metadata:
      labels:
        app: taskconsumer
    spec:
      containers:
      - name: taskconsumer
        image: lidiyaj/taskconsumer
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: taskconsumer
spec:
  type: NodePort
  selector:
    app: taskconsumer
  ports:
  - port: 80
    targetPort: 5000